Remove unroll pragmas on loops with dynamic bounds
oneapi-src/oneDPL pull request #1304
Opened 2023-11-30 19:59 UTC by adamfidel

This PR removes `#pragma unroll` from loops whose bounds are not known at compile time. With the 2024.0.0 compiler, the `merge` algorithm and `scan` family of algorithms now throw runtime warnings during JIT compilation stating that the unroll transformation cannot be performed:

```
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
```

After removing these unnecessary pragmas, the warnings go away.

2023-11-30 20:20 UTC, danhoeflinger approved these changes
This LGTM.  I don't see much risk here, and I think these are all fruitless attempts at unrolling with runtime loop bounds.  

However, with no reason to rush it and such a simple PR, its probably worth waiting for a second opinion.

2023-12-01 08:04 UTC, julianmi approved these changes
LGTM. This resolves all unrolling warnings in our tests.

2023-12-01 09:38 UTC, SergeyKopienko commented
Looks like we still have some amount of this warnings.
For example:
```
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
```

Compiler info:
```
>> icpx --version
Intel(R) oneAPI DPC++/C++ Compiler 2024.0.0 (2024.0.0.20231017)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2024.0/bin/compiler
Configuration file: /opt/intel/oneapi/compiler/2024.0/bin/compiler/../icpx.cfg
```

2023-12-01 09:41 UTC, SergeyKopienko requested changes
Looks like we still have some amount of this warnings (at least on Linux + ixpc).
For example:
```
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
```

CMake command line:
```
cmake -DCMAKE_BUILD_TYPE=release -DONEDPL_BACKEND=dpcpp -DCMAKE_CXX_COMPILER=icpx -DCMAKE_CXX_FLAGS="-fsycl -fsycl-device-code-split=per_kernel" -DONEDPL_DEVICE_TYPE=GPU ..
```

Also we have these warning in our CI: https://github.com/oneapi-src/oneDPL/actions/runs/7051606623/job/19194895255?pr=1304

Are we able to fix the rest of warnings in our tests?

2023-12-01 10:45 UTC, julianmi commented
> Looks like we still have some amount of this warnings (at least on Linux + ixpc). For example:
> 
> ```
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> /test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp:101:1: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
> ```
> 
> CMake command line:
> 
> ```
> cmake -DCMAKE_BUILD_TYPE=release -DONEDPL_BACKEND=dpcpp -DCMAKE_CXX_COMPILER=icpx -DCMAKE_CXX_FLAGS="-fsycl -fsycl-device-code-split=per_kernel" -DONEDPL_DEVICE_TYPE=GPU ..
> ```
> 
> Also we have these warning in our CI: https://github.com/oneapi-src/oneDPL/actions/runs/7051606623/job/19194895255?pr=1304
> 
> Are we able to fix the rest of warnings in our tests?

Thanks, @SergeyKopienko. I don't see warnings on Windows but can reproduce them on Linux. It looks like these warnings occur in the TBB path only. I think this is a different issue and we can address that in a separate PR.

2023-12-01 10:49 UTC, SergeyKopienko approved these changes
Thank you, @julianmi, for discussion about the rest of warning.
Looks like the reason not linked with this PR.
LGTM

2023-12-04 14:09 UTC, merged