[dpc++][pstl] shift_left, shift_right (C++20) mention
oneapi-src/oneDPL pull request #150
Opened 2021-03-09 14:06 UTC by MikeDvorskiy

[dpc++][pstl] + shift_left, shift_right (C++20) mention

2021-03-09 14:35 UTC, capatober submitted a review, later dismissed
I don't have any comments here

2021-03-10 08:27 UTC, capatober submitted a review, later dismissed

2021-03-15 22:33 UTC, dcbenito commented on documentation/library_guide/pstl_main.rst
> +supports the unsequenced execution policy and a couple of additional algorithms - ``shift_left``, ``shift_right``,
and the algorithms ``shift_left`` and ``shift_right``,

2021-03-15 22:36 UTC, dcbenito requested changes
Please see inline comments, and add the updates to the 'release/2021.2' branch so the changes appear for the release.

@AlexVeprev is my above request correct?

2021-03-15 22:36 UTC, dcbenito commented on documentation/library_guide/pstl_main.rst
> +specified in the final draft for the C++ 20 standard (N4860). For more details see `the standard execution
Please change: [specified in the] to [which are specified in the]

2021-04-08 16:13 UTC, AlexVeprev commented
> Please see inline comments, and add the updates to the 'release/2021.2' branch so the changes appear for the release.
> @AlexVeprev is my above request correct?

I'm not tracking release process closely. As far as I know 2021.2 has already been published, so I'd not expect updates there, @ValentinaKats could you please comment?

2021-04-09 11:17 UTC, ValentinaKats commented
> > Please see inline comments, and add the updates to the 'release/2021.2' branch so the changes appear for the release.
> > @AlexVeprev is my above request correct?
> 
> I'm not tracking release process closely. As far as I know 2021.2 has already been published, so I'd not expect updates there, @ValentinaKats could you please comment?

All proposed changes were timely added to 'release/2021.2' branch and were published as part of 2021.2 release documentation. No issues here. I'm closing this PR as these changes were cherry picked from 'release/2021.2' into 'main' in scope of PR #186.

2021-04-09 11:17 UTC, closed without merging

2021-04-09 22:02 UTC, dcbenito commented
Thank you, @ValentinaKats!