Remove cxxopt from dr tests suite
oneapi-src/oneDPL pull request #1573
Opened 2024-05-09 11:18 UTC by mateuszpn

2024-05-13 07:04 UTC, lslusarczyk requested changes
some comments

Since changes shown in github are not strictly the changes you're about to commit I advice to check diff in cmdline by
`git diff origin/distributed-ranges`

Begore doing this please checkout latest brancgh as I've resolved  recent conflicts there.

2024-05-13 07:04 UTC, lslusarczyk commented on test/distributed-ranges/shp/xhp-tests.hpp
> +// #include "cxxopts.hpp"
remove instead of commenting out

2024-05-13 07:07 UTC, lslusarczyk requested changes
seems diff shown in github is correct one now

2024-05-13 07:07 UTC, lslusarczyk commented on include/oneapi/dpl/internal/distributed_ranges_impl/detail/enumerate.hpp
> -  template <rng::viewable_range R>
revert, this is only formatting change

2024-05-13 13:10 UTC, mateuszpn commented on test/distributed-ranges/include/common-tests.hpp
> -                     "    actual: {}\n  ",
These changes were accidental. After manual restoring of relevant snippets, formating may be slightly different, as now it follows LLVM rules, as defined by VC Code

2024-05-14 10:32 UTC, lslusarczyk commented
Removed formatting changes, removed cxxopts header checker from cmake.

2024-05-14 10:34 UTC, merged