Changed include order to make tests work with libstdc++ 9,10
oneapi-src/oneDPL pull request #51
Opened 2020-11-24 13:29 UTC by dparanic

2020-11-24 13:41 UTC, capatober requested changes

2020-11-24 13:41 UTC, capatober commented on test/parallel_api/algorithm/alg.nonmodifying/adjacent_find.pass.cpp
> +
I think this is an extra empty line

2020-11-24 13:41 UTC, capatober commented on test/parallel_api/ranges/copy_ranges_factory_sycl.pass.cpp
>  #include <iostream>
oneDPL headers should be included before <iostream> as well here and for other ranges tests

2020-11-24 13:41 UTC, capatober commented on test/general/lambda_naming.pass.cpp
>  #    include <CL/sycl.hpp>
oneDPL headers should be included before this header as well

2020-11-24 13:41 UTC, capatober commented on test/general/sycl_iterator.pass.cpp
oneDPL headers should be included before these headers as well

2020-11-24 13:41 UTC, capatober commented on test/general/sycl_policy.pass.cpp
>  #endif
oneDPL headers should be included before these headers as well

2020-11-24 13:43 UTC, capatober approved these changes

2020-11-26 11:49 UTC, capatober approved these changes

2020-11-27 10:44 UTC, merged

2020-11-27 10:44 UTC, dparanic commented
Tests are running successfully locally, so I close this PR.